// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UMhT0wzH17oQEZRH_xs-MA_FE6sD3rM',
    appId: '1:1069989675436:web:0940643822a064ad5cfa09',
    messagingSenderId: '1069989675436',
    projectId: 'pelatihanmobile-45f66',
    authDomain: 'pelatihanmobile-45f66.firebaseapp.com',
    storageBucket: 'pelatihanmobile-45f66.firebasestorage.app',
    measurementId: 'G-LF7447B6D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq97JyGNzbPHYwUlol_igadQLkJHxCIFc',
    appId: '1:1069989675436:android:c93af053b1765c775cfa09',
    messagingSenderId: '1069989675436',
    projectId: 'pelatihanmobile-45f66',
    storageBucket: 'pelatihanmobile-45f66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfW1mBj708SO0ZIRsRkRHsYVafDfM8aJw',
    appId: '1:1069989675436:ios:345aa062150f9f0b5cfa09',
    messagingSenderId: '1069989675436',
    projectId: 'pelatihanmobile-45f66',
    storageBucket: 'pelatihanmobile-45f66.firebasestorage.app',
    iosBundleId: 'com.example.myAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfW1mBj708SO0ZIRsRkRHsYVafDfM8aJw',
    appId: '1:1069989675436:ios:345aa062150f9f0b5cfa09',
    messagingSenderId: '1069989675436',
    projectId: 'pelatihanmobile-45f66',
    storageBucket: 'pelatihanmobile-45f66.firebasestorage.app',
    iosBundleId: 'com.example.myAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0UMhT0wzH17oQEZRH_xs-MA_FE6sD3rM',
    appId: '1:1069989675436:web:b22e218bd461e0145cfa09',
    messagingSenderId: '1069989675436',
    projectId: 'pelatihanmobile-45f66',
    authDomain: 'pelatihanmobile-45f66.firebaseapp.com',
    storageBucket: 'pelatihanmobile-45f66.firebasestorage.app',
    measurementId: 'G-YH7Q4PR71Z',
  );
}
